### ISSUE TITLE
DroneCI

### ISSUE THREAD

**Issue by 1995parham** [elahe-dastan/urlShortener_KGS#7]
It would be great to have a continuous integration for **test** and **lint** based on [DroneCI](https://cloud.drone.io/).

Here is a configuration example:

```yml
---
kind: pipeline
name: default

steps:
  - name: lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run --enable-all
  - name: test
    image: golang
    commands:
      - go test -v ./...
```

That must be placed on `.drone.yml`.
